### ISSUE TITLE
Selecting multiple items?

### ISSUE THREAD

**Issue by ragebiswas** [moroshko/react-autosuggest#101]
Hi,
 This component is wonderful and very cleanly designed! I'd like to know if there's a way I can use this component for selecting multiple comma separated items. Is this possible with the current set of options supported?

**Comment by moroshko** [comment]
@ragebiswas Thanks!

Nope, I don't see a way to have a comma separated list. The component is designed to have a single value. You could, however, implement something like this:

* User selects an item from the autosuggest
* On selection, add the selected item to a list that is maintained outside of the autosuggest
* After item is selected, clear the input, so that user could add another item to the list

If you decide to go with this approach, I'd encourage you to use 3.0 beta:

    npm install react-autosuggest@3.0-latest --save

**Comment by ragebiswas** [comment]
Thanks for the reply @moroshko. I'll give it a shot :)
