### ISSUE TITLE
Hinting in the form input

### ISSUE THREAD

**Issue by pjsinco** [moroshko/react-autosuggest#102]
Thank you for this great component. I'm off to a good start with it.

A nice feature would be hinting within the input:

![Hinting](http://i.imgur.com/E7O1y98.png)

I would be interested in a DIY version if anyone has implemented this feature already.

**Comment by 01taylop** [comment]
A quick and dirty solution would be to give your input a transparent background and absolutely position a div behind it using some basic JavaScript to put in the first or highlighted item. With the correct top and left padding, font size and colour it could look quite good. I might experiment tomorrow.

**Comment by pjsinco** [comment]
Thank you—I will give that whirl.

**Comment by moroshko** [comment]
@pjsinco What you ask is basically [`aria-autocomplete="both"`](http://www.w3.org/TR/wai-aria/states_and_properties#aria-autocomplete).

I just checked how Google Drive implemented this behaviour, and it looks like they are using another input element that sits behind the main input and contains the hint text, which is very similar to what @01taylop suggested.

Another possible approach is to use a single input element, and select the hint text instead of making it grey. See [this example](http://rackt.org/react-autocomplete/static-data/).

One thing to keep in mind is that it should gracefully degrade when JS is disabled (this is a progressively enhanced widget), and that introducing the hint text potentially implies more keyboard interactions (e.g., what do you expect to happen when hint text is displayed, and Tab is pressed?).

Do you guys know any good accessible autosuggest examples on the web?

**Comment by moroshko** [comment]
At the moment, I feel like adding the hint behaviour will introduce a significant overhead to the component. Until anyone can prove I'm wrong, and suggest a reasonable implementation, I'm closing this issue.
