### ISSUE TITLE
Simplify Example in README

### ISSUE THREAD

**Issue by damassi** [moroshko/react-autosuggest#103]
It would be nice if the beginning example that you laid out in the README were greatly simplified. Arriving at your page, there is a good amount of code to read through in order to express something that is fairly basic, and it seems like you could be losing users due to this fact. Something like 

```
import React from 'react';
import Select from 'some-select-library';

React.render(
  <div>
    <Select dataSource={[
      'hello',
      'how',
      'are',
      'you'
    ]}
    />
  </div>
, document.getElementById('root')
);
```

would get beginners over the line much quicker than having to see regexs and so on right at the get go. (The above is just pseudocode to illustrate a point.)

**Comment by moroshko** [comment]
@damassi Thanks for your feedback!

Since Autosuggest is a controlled component, you need to specify at least `value`, `onChange`, and of source `suggestions`. I agree that regex should not present in the Basic Usage example.
I'll think about creating a higher order component (that will use the Autosuggest component) with minimal mandatory props, something along the lines of what you suggested.

Since this isn't an issue with the library itself, I'm closing this issue. I'll ping you here once I simplify the Basic Usage example. Thanks again for pushing me to make react-autosuggest better!
