### ISSUE TITLE
How to clear input text box in onSuggestionSelected?

### ISSUE THREAD

**Issue by tc** [moroshko/react-autosuggest#104]
I want to clear the input field after a user selects.

I tried both using a refs value and setting the state:
```
  onSuggestionSelected(event, { suggestionValue }) {
    console.log(suggestionValue);
    this.refs.autoSuggest.value = '';
    this.setState({value: ""});
  }
```
See http://codepen.io/tommychheng/pen/Vezdoo for example.

Any ideas?

**Comment by moroshko** [comment]
@tc You shouldn't need `refs` with Autosuggest. The reason `this.setState({ value: '' });` doesn't seem to clear the input is because after `onChange` is fired immediately after `onSuggestionSelected`, causing the value to be set to the selected value.

You can achieve what you want by getting rid of `onSuggestionSelected` and clearing the value in `onChange` instead using `method`:

    onChange(event, { newValue, method }) {
      this.setState({
        value: (method === 'click' || method === 'enter') ? '' : newValue
      });
    }

[Codepen](http://codepen.io/moroshko/pen/MKvPVv)

I might think about firing `onSuggestionSelected` after `onChange`, which will hopefully simplify things.

**Comment by tc** [comment]
thanks!

**Comment by moroshko** [comment]
@tc Note that starting from version 3.3.2, `onSuggestionSelected` is fired after `onChange`, which allows you to clear the input on selection like this:

    onSuggestionSelected() {
      this.setState({
        value: ''
      });
    }

[Codepen](http://codepen.io/moroshko/pen/JGrGgy)

**Comment by tc** [comment]
great thanks!
