### ISSUE TITLE
Feature request - support clearing the text on input focus

### ISSUE THREAD

**Issue by puspa** [moroshko/react-autosuggest#106]
When user needs to change the value (pre-populated or previously selected) user has to delete existing text first. This is not ideal especially in mobile experience. 

If this can support clearing text when user focuses on input and restore old value on blur if user doesn't make change, that will be ideal.

**Comment by moroshko** [comment]
@puspa You can press ESC to clear the field. You can also add `type="search"` to the input field to have a clear button. If that's not good enough, you could try and implement the desired behaviour yourself by hooking into input's `onFocus`. I don't think that the behaviour that you are describing is a common practice, so adding a special prop doesn't seem appropriate in this case. If you still struggle, please post a Codepen with your code, and I'll try to help.

**Comment by cristobal-io** [comment]
Thanks for react-autosuggest, I think it's really fantastic to have available this tool.

I would like to see an option that shows an `x` button inside the input field as @puspa suggested, maybe a prop `showClearButton`

Seems like the default `type="search"` does not work on all browsers and is [not so standard](https://developer.mozilla.org/en-US/docs/Web/CSS/::-webkit-search-cancel-button), for a quick check we can open on __firefox__ [codepen](http://codepen.io/css-tricks/pen/VYyxRe) with a sample for different input type, it doesn't show the `x` for clearing the content, it does work on __Safari__ and __Chrome__, but it does not work on __iOS__.

Since this package is creating the `input` element and getting all the functionality for autosuggestions, it would be really cool to see this feature enabled, working on desktop and mobile platforms.

**Comment by moroshko** [comment]
@cristobal-io I understand that a clear button can be useful, but not convinced that it should be part of `react-autosuggest`.

You can implement the clear button yourself using [`renderInputComponent`](https://github.com/moroshko/react-autosuggest#renderInputComponentProp). 

[Here](https://github.com/seek-oss/seek-style-guide/blob/d0d54ac45f7fa53e151a20d43d5e04877641a363/react/Autosuggest/Autosuggest.js#L70-L79) is one example of such an implementation. See it in action [here](https://www.seek.com.au/) (the **Where** field).

**Comment by amskathir** [comment]
Hi Moroshko, In my Project I used this autosuggest. But type="clear"  clear button not working in firefox. Please help me.
