### ISSUE TITLE
In IE 11 do not hide suggests after select

### ISSUE THREAD

**Issue by ibhub** [moroshko/react-autosuggest#109]
Steps to reproduce:
1. Open http://react-autosuggest.js.org/
2. Type "c" in Basic suggestion input
3. Select "c#" for example (mouse click only)
4. See issue: "c#" in suggestion don't hide

**Comment by joaovpmamede** [comment]
I wish I could have this feature, not closing the suggestions after an event (click/enter, etc...).
That way we could choose more than one suggestion at a time.

Do you plan on adding some prop for this in the future?

**Comment by dlmoody** [comment]
This also happens in IE10. I have not verified but I have been told that this is occurring in IE9 also.
@moroshko I would be more than happy to make the fix. Does anyone know what the issue is? I am thinking the fix would be in autowhatever though right? Since it seems to be presentation layer so to speak?

**Comment by moroshko** [comment]
@joaovpmamede What you want is probably beyond the scope of this library, sorry.

**Comment by moroshko** [comment]
@dlmoody I haven't had the time to investigate the IE issue, but will be more than happy to accept a fix.

**Comment by moroshko** [comment]
Fixed in [3.7.1](https://github.com/moroshko/react-autosuggest/releases/tag/v3.7.1)

**Comment by ibhub** [comment]
Great! Thank you.
