### ISSUE TITLE
Changing `focusInputOnSuggestionClick` to `focusInputOnSuggestionPick`

### ISSUE THREAD

**Issue by sushant711** [moroshko/react-autosuggest#134]
Sorry for creating a new issue again but I think some of things can be fixed here,

In the method `focusInputOnSuggestionClick`, the behavior is restricted to mouse click. The intended behaviour is whenever a suggestion is picked regardless whether its a mouse click, or a enter press, it should behave same for focusInput.

Also, Autosuggest (which is wrapped inside AutosuggestContainer) has a prop called `isCollapsed`. When I pick a suggestion, the input is focussed, but suggestions are not appearing since isCollapsed is set to true. Is there someway I can make a mandate not to collapse it ever.

**Comment by moroshko** [comment]
@sushant711 Could you please open 2 separate issues, if you ask 2 unrelated questions?

`focusInputOnSuggestionClick` is targeting onClick and onTap by design, not Enter.

When suggestion is selected, the list should be closed according to accessibility guidelines. If you want the list to always stay open, you might need to look for another library, or implement your own.
