### ISSUE TITLE
Add tabToEnter setting

### ISSUE THREAD

**Issue by rickhanlonii** [moroshko/react-autosuggest#163]
Certain flows allow both tab and enter to complete a suggestion (e.g. Slack user mentions). It would be great if there was a setting to allow this.

**Comment by moroshko** [comment]
I must admit that I'm a bit confused with the functionality you are trying to achieve. As far as I can see, pressing Tab in Slack is somewhat equivalent to pressing Down, not pressing Enter, i.e. it moves to the next suggestion rather than selecting the focused one. The URL bar in Chrome behaves the same. [Closing this for now.](https://github.com/moroshko/react-autosuggest/pull/164#issuecomment-217735323)
