### ISSUE TITLE
renderSuggestion called too many times

### ISSUE THREAD

**Issue by fredrikoe** [moroshko/react-autosuggest#193]
In my project I noticed the UI renders pretty slowly when I have like 100 or more elements in the search result and started logging a bit to the console. It turns out that `renderSuggestion` was called not only when the input field changes but also when the mouse moves. Is it possible to prevent this easily or is it a bug?

Here is a Codepen example that shows this (open the console and move the mouse around when a search result is shown): http://codepen.io/fredrikoe/pen/PzjBgp

**Comment by moroshko** [comment]
@fredrikoe Good point. I totally agree that `renderSuggestion` is called too many times at the moment, and there is a room for optimization. 

`react-autosuggest` depends on `react-autowhatever`, and it looks like the same issue exists in `react-autowhatever` where the equivalent `renderItem` function is called too many times.

My gut feel is that if, for example, we render 100 items, then mouse hovers should cause at most 2 calls to `renderItem`: the item the loses focus and the item that gets focus.

I'm not sure what the fix is yet, but you are welcome to submit a PR to [`react-autowhatever`](https://github.com/moroshko/react-autowhatever).

**Comment by moroshko** [comment]
@fredrikoe This has been fixed in react-autowhatever 4.1.0. I hope to release a new version of react-autosuggest soon that fixes your issue.

**Comment by moroshko** [comment]
@fredrikoe I just published [3.9.0](https://github.com/moroshko/react-autosuggest/releases/tag/v3.9.0) which should solve your issue. Could you please test and let me know how you go?
