### ISSUE TITLE
Append the selected value to existing input value

### ISSUE THREAD

**Issue by zarmeen92** [moroshko/react-autosuggest#202]
Hello
I have a use case : I want to append the selected suggested value with the existing value of  input field.Currently it is clearing whatever I have written previously and then add the selected value to input field

I tried to override onSuggestionSelected but its not working the way I want

```js
const inputProps = {
      value,
      onChange: this.onChange,
      ref : "msg" ,
      className :"form-control input-sm" ,
      placeholder :"Type your message here...",
      
    };

onSuggestionSelected({ suggestion, suggestionValue})
{
  console.log("current value of input is  :" + this.refs.msg.value)
   this.setState({
      value: this.refs.msg.value + " " + suggestionValue
    });
}
```

**Comment by moroshko** [comment]
You should be using the same `value` you are providing to `inputProps`, rather than `this.refs.msg.value`. Also note that `onSuggestionSelected` gets the `event` as the first parameter, so you should be destructuring `suggestionValue` from the second parameter. See [this](http://codepen.io/moroshko/pen/WxrBWJ) Codepen for example.

Just curious, what's your use case for appending the input value and the selected suggestion?

**Comment by zarmeen92** [comment]
thanks!
I am applying auto suggestion on word written in input field rather than complete value of input. That's why  I want to preserve previous words already written in input field.
