### ISSUE TITLE
Hitting ENTER hides the dropdown

### ISSUE THREAD

**Issue by shprink** [moroshko/react-autosuggest#206]
Hi,

easily reproducible http://codepen.io/moroshko/pen/WryOMP

* type the letter C
* hit enter

the result dropdown disappears

Expected behavior: dropdown still visible

Is there a way to hack this using #180 `onKeyDown` example?

thanks

**Comment by moroshko** [comment]
We used to leave the suggestions open in this case, but this changed in #171.

What's your use case for not hiding the suggestions when Enter is pressed?

**Comment by shprink** [comment]
If you type something and hit enter you could have the results display fo few ms and then it hides. It feels broken.

**Comment by shprink** [comment]
It is even more frustrating with async operations. Can this behavior be an option?

**Comment by moroshko** [comment]
@shprink I struggle to see the problem. Could you create a Codepen to demonstrate your frustration?

**Comment by shprink** [comment]
let's close this :)

**Comment by shprink** [comment]
It is easy. In the DOM the input and the drop down are always siblings. I
want to be able to change that.

**Comment by Magellol** [comment]
I'm actually facing an issue and it's a bit more annoying on mobile.
I have this field that fetches async suggestions upon keystrokes and proposes stuff based on the actual value. I don't have any other way to navigate after, you gotta choose a suggestion. By having the dropdown closing on hitting Enter, we have a weird experience on mobile because the keyboard would show up on input focus and tapping `done` simulates a Enter, which hides the suggestions so you can really select anything.

Any way to make it as a boolean prop or something? So we can opt in if wanted?

Ref iOS keyboard:
<img width="249" alt="screen shot 2017-07-05 at 7 27 36 pm" src="https://user-images.githubusercontent.com/3819093/27889079-1b160aee-61b8-11e7-9a75-3a114b1c31dc.png">

**Comment by moroshko** [comment]
@Magellol The role of the Autosuggest is to suggest you some options you might want to choose to save you from typing the whole thing. 
Autosuggest doesn't force you to select one of the suggestions. Free text will always be allowed (think Google search).
If you want to constrain users to select one of the predefined options, consider using [react-select](https://github.com/JedWatson/react-select).

**Comment by Magellol** [comment]
@moroshko Fair enough. I was able to workaround something but thanks for suggesting another library that might suit best my needs 👍
