### ISSUE TITLE
Add initialSuggestions prop

### ISSUE THREAD

**Issue by ImanMh** [moroshko/react-autosuggest#207]
That would be awesome to have the ability of defining an array for initial suggestions. For example in a sport selector: 

```js
initialSuggestions: [
  { name: 'football' }, 
  { name: 'basketball' },
  { name: 'volleyball' },
  { name: 'biking' }
]
```
Now if user focuses the input these suggestions should be  automatically displayed without the need for typing anything. This can be a great UX improvement.

**Comment by moroshko** [comment]
@ImanMh It's totally up to you to decide what suggestions to render when the input is blank. 

You just need to remember to set [`shouldRenderSuggestions`](https://github.com/moroshko/react-autosuggest#shouldRenderSuggestionsProp) to always return `true`, because by default it returns `false` when the input is blank. 

Then, all you need to do is to provide the "initial suggestions" via [`suggestions`](https://github.com/moroshko/react-autosuggest#suggestions-required) when the input is blank. 

[Here](http://codepen.io/moroshko/pen/kXpapq) is a working Codepen that demonstrates how to achieve this.

Does this help?

**Comment by ImanMh** [comment]
Thanks for such a detail answer. That is exactly what I was looking for.
