### ISSUE TITLE
Input container

### ISSUE THREAD

**Issue by shprink** [moroshko/react-autosuggest#220]
Hi,

now that we have [renderSuggestionsContainer](https://github.com/moroshko/react-autosuggest#renderSuggestionsContainerProp) (which is really useful!) another great feature would be to have a `renderInputContainer` to do the same but for the input. 

For instance I want my input (only, not the results) to be included within another component:

![image](https://cloud.githubusercontent.com/assets/1388706/17816382/2afb9dd2-6639-11e6-819e-12ed40b840b9.png)

**Comment by angelo-v** [comment]
This should be solved with PR #263

**Comment by moroshko** [comment]
`inputComponent` is available in [v6.1.0](https://github.com/moroshko/react-autosuggest/releases/tag/v6.1.0) now.

**Comment by shprink** [comment]
Thanks 💯 !

**Comment by ZebraFlesh** [comment]
So is the correct usage of `inputComponent` to still specify `inputProps`? Or are `inputProps` no longer required if you're using `inputComponent`?

**Comment by moroshko** [comment]
@ZebraFlesh 
`inputProps` is still required as usual when using `inputComponent`. 

Autosuggest needs to set some aria attributes to the input element in order to keep it accessible.

You should pass your usual `inputProps` (e.g. `value`, `onChange`).
Autosuggest will merge it with what's needed for accessibility, and will pass the merged props to `inputComponent`.
All you have to do then, is to pass through all the props you get in `inputComponent` to the underlying input element.

I hope this makes sense. I'll update the docs to clarify this.
