### ISSUE TITLE
Suggestions list via props instead of callback for flux data flow?

### ISSUE THREAD

**Issue by anyong** [moroshko/react-autosuggest#27]
Is there any way of doing this? I really like the component because it's the easiest autocomplete I tried, looks great, and has full ARIA support - lots of things to like!

What would be even better is a lightweight version that simply takes in the suggestions as a prop, but everything else remains as is. I originally tried putting a flux action call in the `suggestions` function, but since fluxible returns the results of actions onto props, I didn't have a good way of calling the callback after the props became available. I was trying to fool around in the source a bit to see if I could get it working but didn't quite get there... is this something you would think about adding in the future? For now I'm adding my calls to the server directly into the component, but I'd really like to take those out in the future.

Thanks!

**Comment by moroshko** [comment]
@anyong I'm not very familiar with fluxible. Could you share some code to illustrate the issue?

**Comment by anyong** [comment]
Essentially the actions used in fluxible do not allow callbacks to be run by design, so that actions can be purely fire-and-forget, allowing for a better flux flow. In this case, any things like async data will come into a component as props after the action->store->update view cycle is complete.

Here's the problem:

```js
var getSuggestionsAction = require('./getSuggestions');
var component = React.createClass({
  getSuggestions: function(input, callback) {
    this.context.executeAction(getSuggestionsAction, input);
    // now, there is no way of knowing when the result (later coming in via props, say
    // this.props.suggestions, for example) will be available.
    callback(this.props.suggestions); // if it fires too early, this.props.suggestions is still null

    // i tried to fix this by doing something like:
    function wait() = {
      setTimeout(function() {
        if (this.props.suggestions) callback(this.props.suggestions);
        else wait()
      }, 300);
    }
    wait();

    // but it's a hack and doesn't work well, especially the cached results for the current state
    // of the input value get messed up.
  },
  render: function () {
    return <Autosuggest suggestions={this.getSuggestions}/>
  }
```

**Comment by moroshko** [comment]
@anyong Thanks for explaining! 

I'm a bit confused with your example though. You have the props `suggestions` here:
```js
<Autosuggest suggestions={this.getSuggestions}/>   // suggestions is function here
```
and also here: (array of suggestions)
```js
callback(this.props.suggestions); // suggestions is an array here
```
These 2 props shouldn't have the same name, right?

Happy to help to make react-autosuggest flux friendly.

**Comment by anyong** [comment]
They are two different props. `this.props.suggestions` would be the
suggestions props coming into the current component via flux, while the
`suggestions={this.getSuggestions}` is a prop of the child Autosuggest
component.

I would ideally like to write:

```
<Autosuggest suggestions={this.props.suggestions}/>
```

Where `this.props.suggestions` is the actual list of suggestions, not a
function. No callbacks necessary.

**Comment by moroshko** [comment]
@anyong Oh, my bad... Now it makes sense.

At the moment, `<Autosuggest />`'s `suggestions` is a function, and I feel like allowing it to be an array is probably not a good idea. Normally, every `prop` would have a predefined type that can be verified with `PropTypes`. So, I would be inclined to leave `suggestions` as a function:

```xml
<Autosugest suggestions={this.getSuggestions} />
```

```js
import getSuggestionsAction from './getSuggestions';
...
getSuggestions(input) {
  this.context.executeAction(getSuggestionsAction, input);
}
```

Note that `<Autosuggest />` wraps the given `suggestions` function in a debounce (of 100ms), so your flux action won't be executed on every keypress if user types really fast.

Until now, no change is required.

Now, the question is how do we pass the suggestions themselves to `<Autosuggest />` via its `props` (that's what fluxible gives you for free, right?).

The only way I can think of at this point is to add a new prop to `<Autosuggest />`, for clarity sake say `suggestionsArray`:

```xml
<Autosugest suggestions={this.getSuggestions} 
            suggestionsArray={this.props.suggestionsArray} />
```

Potentially, in version 2.0 we could change the prop names to be:

```xml
<Autosugest suggestions={this.props.suggestions} 
            getSuggestions={this.getSuggestions} />
```

But, this is a separate story.

The biggest issue that I see at this point is caching. `<Autosuggest />` caches results, so that if you typed `ab`, clicked Backspace and then `b`, the old `ab` results would be displayed. `<Autosuggest />` also handles delayed requests for you. For example, imagine that the AJAX request for the query `ab` is delayed for some reason. Meantime, user types `c`, and the results for `abc` are back and displayed. Now, finally, the results for `ab` are back. These should be ignored and not displayed because they are not relevant anymore. `<Autosuggest />` handles this for you.

How would you go about caching when using flux? Shall the caching logic leave outside of `<Autosuggest />`? Would be happy to hear your opinion.

Meantime, as a workaround, I would suggest to have the AJAX request inside your component.

```js
class YourComponent extends React.Component {
  getSuggestions(input, callback) {
    // make AJAX request here and then: callback(null, retrievedSuggestions)
  }
  render: function () {
    return (<Autosuggest suggestions={this.getSuggestions} />);
  }
}
```
Even though it breaks the flux architecture, I'd prefer this as it would probably give you more predictable results than the `setTimeout` hack you shown above.

**Comment by anyong** [comment]
Yes, putting the AJAX call inside of my component is what I've done for the moment - not entirely happy with it but it does get the job done.

Yes of course the caching issue is noticeable right away when you try to implement it like I did. I don't particularly see a reason why the cache can't live outside of the Autosuggest and inside of the data store, which is probably where it should live in a flux model.

I would simply pass the cache in as a prop as well and check it directly before deciding which action to fire. The final result would be something like this:

```js
class SomeComponent = React.createClass({
    isCached(input) {
        this.props.cache.forEach(function (cachedResult) {
            if (cachedResult.input === input) {
                return cachedResult.suggestions;
            }
        });
    },

    suggestions(input) {
        if (this.isCached(input)) {
            this.context.executeAction(getCachedSuggestions, input);
            return;
        }
        this.context.executeAction(getNewSuggestions, input);
    },

    render () {
        return (<Autosuggest suggestions={this.suggestions}
                             suggestionList={this.props.suggestions}
                />);
    }    
});

class DataStore = createStore({
    getCachedSuggestions (input) {
        this.cache.forEach(function (c) {
            if (c.input === input) {
                this.suggestions = c.suggestions;
            }
        })
        this.emitChange();
    },

    // API call has already happened here in the action,
    // newSuggestions is the data returned from the server
    getNewSuggestions (input, newSuggestions) {
        this.cache.push({input: input, suggestions: newSuggestions});
        this.suggestions = newSuggestions;
        this.emitChange();
    }
});
```

What do you think?

**Comment by tpievila** [comment]
Giving a list of suggestions as a prop would also help us to create nested suggestions: input "Foo" would first give choices "Fooroad, Bartown", "Fooroad, Baztown" and "Foostreet, Bartown", and after selecting one the list would change into "Fooroad 1, Bartown", "Fooroad 5, Bartown" and so on. Of course it would be pretty useful to be able to prefill, or otherwise change the input value too.

**Comment by moroshko** [comment]
@anyong Unfortunately, when `<Autosuggest />` was designed, I didn't have the flux mindset yet. I wanted it to be a plug-and-play component that gives you things like caching and debounce out of the box. Of course, we could start taking these things out of the component, and implement them ourselves, but I feel that it would become a completely different component then. Maybe we could have 2 components: the current one for people that don't use flux, and another one for those that do. The user will decide which one to use. I feel like trying to adapt the current component to work with flux architecture will result in a complicated API. If you think otherwise, feel free to submit a Pull Request.

**Comment by moroshko** [comment]
@tpievila What you are trying to achieve is beyond the scope of autosuggest. See #13.

**Comment by tpievila** [comment]
Would you still consider a PR, per the previous comment? We have to implement this sooner or later, though I have to check if using react-autosuggest makes sense as a starting point and how much I have to change.

**Comment by moroshko** [comment]
@tpievila I'm not sure I understand your proposal. Could you describe how would you like Autosuggest to look like to satisfy your needs?

**Comment by tpievila** [comment]
The problem is that only way to give suggestions to the component is when it asks for them, via the callback given to suggestions function. But when a suggestion is selected, there is no way to show a new set of suggestions.

If the suggestions were props instead, then the parent component could rerender the Autosuggest component. Of course there could be other ways to do this.

**Comment by moroshko** [comment]
Ideally, Autosuggest would support both flux and non-flux architectures. Unfortunately, at the moment, flux is not supported. Is anyone keen to help designing Autosuggest to support flux? I'm be interested to see an example that uses [redux](https://github.com/gaearon/redux), for example.

**Comment by CalebMorris** [comment]
So I currently use react-autosuggest with Reflux and made a branch from react-starter to show how I have it set up: https://github.com/CalebMorris/react-starter/tree/reflux.

The main things that are the structure are in `app/{stores,actions,api,components/Autocomplete.jsx}` with most logic in the component.

Whenever the input query changes, I update the state for the query, which re-renders the `react-autosuggest` component which calls my search method.
This calls a search Reflux action which is handled by the store.
The store calls to the REST API which responds with whatever I want to display and calls a response Reflux action which the component listens to.

If you want to try it out yourself: clone it, `npm install`, `npm run dev-server` in one terminal, `npm run start-dev` in another terminal, hit `127.0.0.1:8080`.

**Comment by moroshko** [comment]
react-autosuggest 2.0 is out! It supports controlled behaviour.

Flux/redux support will be added in 3.0. See the [3.0 branch](https://github.com/moroshko/react-autosuggest/tree/3.0) for work in progress.

**Comment by moroshko** [comment]
Just wanted to let you know that 3.0 alpha version is available on npm:

    npm install react-autosuggest@3.0.0-alpha.1 --save
