### ISSUE TITLE
Examples are very complex for beginners

### ISSUE THREAD

**Issue by adrianmcli** [moroshko/react-autosuggest#303]
This project needs to have a much better "basic" example.

I was working on an existing application where the previous developer just copy and pasted the code from one of the examples. It was an absolute nightmare because there were a number of features being built on top of what was already a super complex example.

### Problem

If you take a look at the code for the current ["Basic" example](http://codepen.io/moroshko/pen/LGNJMy), you'll notice all sorts of stuff that just gets in the way. First of all, there's an unnecessarily long list of suggestions, and secondly there's an extra function for handling Regex. None of this stuff has anything to do with just getting a suggestion component running.

### Solution

What we need is something that'll literally just render to the screen and show a static list of suggestions.

I created a commented example gist here: https://gist.github.com/adrianmcli/67e29eab8ac839c4011e70d92a1c08d2

The idea is to have code at the same level as a hello-world example. We only focus on getting something showing on the screen. As such, the main purpose of this example was to:

1. Have `react-autosuggest` render itself properly.
2. Have `react-autosuggest` render some kind of suggestion (even if the suggestion is the same no matter what).

I can't stress how important it is to have an example that's ultra-barebones with the sole goal of just getting something to show up on the screen first.

**Comment by moroshko** [comment]
@adrianmcli Thank you for your feedback!

The [Basic Usage](https://github.com/moroshko/react-autosuggest#basic-usage) example in the README is very similar to your gist. The main difference is how `getSuggestions()` is implemented. I tried to demonstrate a simple **yet realistic** implementation of an autosuggest.

I do understand the importance of Hello World type examples. The main reason why examples look complex is because Autosuggest is a [controlled component](https://facebook.github.io/react/docs/forms.html#controlled-components). We could potentially add an [uncontrolled](https://facebook.github.io/react/docs/uncontrolled-components.html) autosuggest component to this library, and then examples should become much simpler.
