### ISSUE TITLE
v7.1.0 doesn't focus suggestions on hover

### ISSUE THREAD

**Issue by snakeyak** [moroshko/react-autosuggest#313]
Hi,

I've just upgraded from 7.0.1 to 7.1.0. It appears 7.1.0. does not focus options on mouse hover, see gifs below:

7.1.0.:
![710](https://cloud.githubusercontent.com/assets/12460995/21594647/498ff912-d125-11e6-9702-0beecbc7e7cc.gif)

7.0.1:
![701](https://cloud.githubusercontent.com/assets/12460995/21594666/84be2072-d125-11e6-9425-28fdd690ad93.gif)

Do I need to update some code on my side or is this a bug in the new version?

Thanks

**Comment by moroshko** [comment]
Weird... I can't reproduce the issue on my side.
Could you try to create a minimal Codepen please that demonstrates the issue?

**Comment by snakeyak** [comment]
I really struggled to create the codepen. Although I believe I found a solution - adding a simple style

`.react-autosuggest__suggestion:hover {
  background-color: #ddd;
}`

does seem to do the trick (don't know how that is connected to 7.1.0..)

**Comment by evan-wheeler** [comment]
I have been working on this for the past two days.  I noticed that it is caused by the deps update, specifically to React-Redux 5.0.1.  I think it *might* have to do with the nesting of providers since the Autosuggest is also connected to its own store. If this is the root cause, React-Redux now has a fix for it:  https://github.com/reactjs/react-redux/issues/582

**Comment by evan-wheeler** [comment]
I think this issue is caused by recent optimizations in `react-redux`.  If an ancestor of the autosuggest is wrapped with a Provider, changes to autosuggest's embedded redux store are getting suppressed since the props into the connected component haven't actually changed and don't result in a UI update.  The reason the rest of the actions work with autosuggest is that the callback props onChange, onSuggestionsFetchRequested, etc. are  forwarded to the outer redux store, which does result in a UI update.  

If `onSuggestionFocused` callbacks were still provided, it would be possible to dispatch those to the outer store, resulting in a prop change which would update the UI, but that is a lot of boilerplate that seems unnecessary.  I'm not convinced that embedded a connected redux stores in a library is a good idea.

However, one simple way to get around this is to just wrap Autosuggest with an empty connect call:
 
```
const FixedAutosuggest = connect()( Autosuggest );  // <------- Wrap autosuggest with connect.

const FooComponent = (props) => 
    <div>
        <FixedAutosuggest ...autosuggestProps />
    </div>;
...
```

This wrapped connect injects `dispatch` but doesn't listen to the store, so I think it simply allows the inner store's updates to result in UI updates.  This seems to completely fix the problem for me.

**Comment by moroshko** [comment]
`redux` and `react-redux` dependencies were removed in [v8.0.0](https://github.com/moroshko/react-autosuggest/releases/tag/v8.0.0). 

Could you please upgrade and verify that the issue is gone?

**Comment by evan-wheeler** [comment]
Yes, it is fixed.  Thank you!
