### ISSUE TITLE
improve Documenteation for alwaysRenderSuggestions

### ISSUE THREAD

**Issue by timlogemann** [moroshko/react-autosuggest#324]
I think the documentation for `alwaysRenderSuggestions` is unclear, because I can't figure out for the life of me how to get it working.
The documentation has the following notice:
"**Important**: Make sure to set the initial value of `suggestions` to match the initial value of `inputProps.value`."

But I think that it is too vague and could be accompanied by a code example. Which `suggestions` is the documentation referring to? The property of Autosuggest? The Property of the state?

If anybody could expand on the documentation and explain to me what it is that I'm not doing correctly that would be great!

* [Codepen here](http://codepen.io/timlogemann/pen/jyJGZx)

* Provide the steps to reproduce the issue, e.g.:
  1. Confirm that Autosuggest has property alwaysRenderSuggestions={true}
  2. Focus on the input field
  3. Press <kbd>Escape</kbd>

  **Observed behaviour:** Nothing happens

  **Expected behaviour:** Suggestions open on focus

**Comment by moroshko** [comment]
`suggestions` in the documentation always refer to the prop of Autosuggest. 

In your example:
* `suggestions` are coming from `state.suggestions`
* `inputProps.value` is coming from `state.value`

So, you need to make sure that the initial value of `state.suggestions` match the initial value of `state.value`

What does "match" mean? It's simply the answer to the following question:
> When input's value is `''` (this is the initial `state.value` defined in the constructor), what suggestions should I see?

In your example, you said that you don't want to see any suggestions:

```js
this.state = {
  value: '',
  suggestions: [] // I don't want to see suggestions
};  
```

Moreover, when you type in the input field, and then remove all the characters, you won't see any suggestions because of this bit in `getSuggestions()`:

```js
if (escapedValue === '') {
  return []; // I don't want to see suggestions when input is blank
}
```

To fix this, first ask yourself:
> Which suggestions should I see when input is blank?

Let's assume that you want to see all the suggestions.

So... First, delete these 3 lines:

```js
if (escapedValue === '') {
  return [];
}
```

Now, `getSuggestions()` will return all the languages when `value` is blank.

You could also do this, if it makes it clearer:

```js
if (escapedValue === '') {
  return languages;
}
```

Note, that we haven't addressed this yet:
> Make sure to set the initial value of `suggestions` to match the initial value of `inputProps.value`.

To address this, change:
```js
this.state = {
  value: '',
  suggestions: [] // I don't want to see suggestions
};  
```
to be:
```js
this.state = {
  value: '',
  suggestions: getSuggestions('') // Now the initial value of suggestions will be all languages, which matches what we want
};  
```

[Codepen](http://codepen.io/moroshko/pen/BpbPWP?editors=0010)

Hope this helps.

**Comment by timlogemann** [comment]
Thanks, your explanation really helped. I kept thinking match was meant in the literal sense of the word meaning suggestions should be `''` as well, which made no sense to me. Now I get it.

In the end all I wanted was to show all suggestions on focus, which has been resolved by setting `alwaysRenderSuggestions` to `true` and removing the `escapedValue` if statement.
But I'm glad you explained the match part as well, as that was the part giving me trouble.
