### ISSUE TITLE
Need to disable caching

### ISSUE THREAD

**Issue by mbektimirov** [moroshko/react-autosuggest#36]
Hi! The forced caching solution looks strange for many reasons and breaks desired behavior of the component. Could you please add an option to disable it?

**Comment by moroshko** [comment]
@mbektimirov Thanks for raising the issue. I was waiting for someone to raise that :) Could you share  your use case for not wanting to cache the results?

It should be easy to add a `disableCache` prop to the component. Feel free to submit a Pull Request. Otherwise, I'll have a look when I get some free time.

**Comment by moroshko** [comment]
@mbektimirov `cache={false}` is added to 1.18.0. Enjoy!

**Comment by mbektimirov** [comment]
Nice! Thank you!
