### ISSUE TITLE
Have onChange include the value if appropriate

### ISSUE THREAD

**Issue by raybooysen** [moroshko/react-autosuggest#381]
When onChange is raised, there is a potential that it matches an item that is in the available set of suggestions.

If it does match, it would be useful for the onChange handler to not only include the string value that was typed, but the matching suggestion.  This would mean that consumers would not have to do another lookup to find the suggestion that was chosen.

This is common when the suggestions are a list of complex objects that are acted upon once an item is selected.

**Comment by moroshko** [comment]
Sorry, I can't clearly see the use case you are trying to solve.
Could you please create a Codepen that demonstrates the issue?

**Comment by ONE75** [comment]
I think @raybooysen is referring to an implicit 'onSelected'. Even without 'selecting' the value, it's possible to have a match in the suggestions.

**Comment by raybooysen** [comment]
That is exactly it.  How can I tell if a user selected an item (and pass that item to the function) vs. just the textual value of the selected value.

**Comment by ONE75** [comment]
@raybooysen I think the problem would be "what's the definition of _the same_". Imagine you have a list with cities and a user is searching for "Hoboken". You find one in the list (Hoboken, USA) but I mean (Hoboken, BE). This would be perfectly possible by a custom render method.

Do you want "Hoboken, USA" to be the selected value because that's the one that (textually) matched? 

I encountered the same problem yesterday and decided to require an explicit "selection" by the user (enter/click). It's a lot simpler and I don't think it's a problem for users of the application (UX testing needed).

As a side node: I don't update the input field when a user "highlights" a suggestion in the list because that would give the impression it's "selected" (which is not the case)
