### ISSUE TITLE
Results only show for a second

### ISSUE THREAD

**Issue by dylmye** [moroshko/react-autosuggest#390]
I'm sorry if this has already been fixed in a closed issue but I'm not sure what to search.

I adapted the language example (from [here](https://github.com/moroshko/react-autosuggest#basic-usage)) to pull from an API (airtable). It returns an array of objects, each object being `{id: 'string', name: 'string', location: 'string'}`.

For whatever reason the dropdown showing the autocomplete results only shows on a keystroke, after a backspace, or sometimes randomly. I'm not sure if this is an error with the example of if I've broken something.

[Adapted code](https://github.com/dylmye/pelleglobe/blob/develop/src/pages/AutocompleteTest/index.js)

[Adapted code hosted (see my issue)](https://pelleglobe-testing.herokuapp.com/autocomp-test)

Thanks.

**Comment by moroshko** [comment]
Could you please create a Codepen, similar to [this one](https://codepen.io/moroshko/pen/LGNJMy), that demonstrates the issue?

**Comment by dylmye** [comment]
https://codepen.io/anon/pen/yXoxOr

I added a console.log to show the outcome of `languages.filter(language => regex.test(language.name))` and for my example, `formattedRecords` just before these values were returned. Here's the outcome:

![left - basic codepen. right - my codepen with airtable addition](https://user-images.githubusercontent.com/7024578/27502945-c192613a-586f-11e7-800a-0a346532c3d2.png)

**Comment by moroshko** [comment]
The problem is that in `onSuggestionsFetchRequested` you set the state to `[]` because the API response is not ready yet. 
When the response is ready, you populate `formattedRecords`, but the state doesn't change. Hence, Autosuggest still shows the last state you set, which is `[]`.

To fix this, you need to set the state **after** the API response is ready, not before.
You could check the [Get suggestions asynchronously](https://codepen.io/moroshko/pen/EPZpev?editors=0010) example to see how it's done.

Here is how you could fix your code: [Codepen](https://codepen.io/anon/pen/OgjBpK?editors=0010)

**Comment by dylmye** [comment]
ahhh sorry, i'm not so great with promises and such. I'm still learning.

Thanks for the really helpful response, I understand a lot better now. :)

**Comment by moroshko** [comment]
You are welcome!
