### ISSUE TITLE
Upgrade docs from 1.18.3 to 9.3.2

### ISSUE THREAD

**Issue by bytor99999** [moroshko/react-autosuggest#457]
Just curious if there is any documentation on deprecations/changes that we need to do in our code to upgrade to the latest version of react-autosuggest. We have a dev working on our upgrade that is having difficulty determining what we need to change.

Thanks

Mark

**Comment by moroshko** [comment]
`react-autosuggest` was rewritten a couple of times since 1.18.3. You can see the changes [here](https://github.com/moroshko/react-autosuggest/releases).

But, honestly, I think it would be easier to start from scratch and implement the latest version of `react-autosuggest` following the [docs](https://github.com/moroshko/react-autosuggest/blob/master/README.md#basic-usage) and the [Codepen examples](https://codepen.io/collection/DkkYaQ/).

**Comment by bytor99999** [comment]
Thanks for the quick response. I think our issue is that back then someone created a custom component in our code that extends AutoSuggest and we are trying to start from scratch. I think the first attempt was to use this custom class that extends it and encapsulate the changes such that the code in the other parts of our application could be relatively unchanged. But I don't think that will work.

So I am going to try and learn the new way and see if I can change all the places that uses it. It is just very complex to do, we have one addressPicker component that is actually 5 subclasses down. Yep, different versions of addressPickers where each is an extension of the other. 👍
