### ISSUE TITLE
Creating a No Match Found inside the dropdown

### ISSUE THREAD

**Issue by Ramosh96** [moroshko/react-autosuggest#484]
Hi, I was wondering how you would create a "no match found" message when the input is focused on. When I type a value inside my AutoSuggest component, if there is no match to the existing suggestions, the dropdown disappears. But I want a "No match found" message to appear in the dropdown. I have implemented it with multiSelect, so it seems like a section title and suggestions are required, but I just want one message to appear

**Comment by moroshko** [comment]
You can implement this outside of the Autosuggest: [Codepen](https://codepen.io/moroshko/pen/wMRmmM)

**Comment by oyeanuj** [comment]
@moroshko I came here looking for something similar to this (and #480). I need a footer as well but since the footer has a call to action ('Add'), it needs to be keyboard accessible. It seems like if you include just in the suggestions container, then the keyboard focus goes from the last result back to the input box rather than to the 'footer'. 

I could possibly always include it as the last value of every search result but that feels like bit of a hack - do you have any suggestions on how best to do while maintaining keyboard accessibility?

**Comment by moroshko** [comment]
@oyeanuj Having the 'Add' action as the last suggestion is your best option for now.
