### ISSUE TITLE
Feature request: easy clearing of value after a selection has been made

### ISSUE THREAD

**Issue by nitelite** [moroshko/react-autosuggest#61]
I have looked through some of the issues that seem to have to do with this scenario, but none of them seemed to give a very easy way to clear the value in the input, from what I could see.

Maybe implement a public reset() method that can be called from the onSuggestionSelected in situations where the callback is running in the parent component? This makes a lot of sense in applications where you are entering a value, pressing down arrow and hitting enter and then are expected to proceed to type another value and repeat the process again.

This would match very well with the first example under Benefits at https://facebook.github.io/react/docs/more-about-refs.html#benefits

If there already is an easy way to do this, I most certainly will accept pointers in the right direction as well.

**Comment by moroshko** [comment]
@nitelite Looks like what you need is a [controlled](https://facebook.github.io/react/docs/forms.html#controlled-components) behaviour. `react-autosuggest` [2.0](https://github.com/moroshko/react-autosuggest/tree/2.0) will support controlled components. I hope to release 2.0 soon, but you are more than welcome to try it out now. The API is pretty stable. The relevant docs section for controlled behaviour is [here](https://github.com/moroshko/react-autosuggest/tree/2.0#value-optional). Hope it helps.

**Comment by moroshko** [comment]
react-autosuggest 2.0 is out! It supports controlled behaviour.

**Comment by approots** [comment]
I'd like to clear the autosuggest input after a selection is made (using controlled behaviour), but I'm unable to do it cleanly. 

My `onChange` handler works in the usual way - it always resets the autosuggest `value` property which obviously updates the autosuggest input. So the problem is, if I set the value property to an empty string in the `onSuggestionSelected` handler, the `onChange` handler still fires and sets it back to the last selection. I don't know a way to prevent the `onChange` handler from executing, or to notify the `onChange` handler to set the value to an empty string.

Actually, a `setTimeout` in the `onSuggestionSelected` to update the value after a delay works, but is there a better way?

**Comment by moroshko** [comment]
@approots I'm afraid using `setTimeout` is the best you can do in 2.x.

I'd encourage you to upgrade to 3.0. It has a much greater control on the component.
You'll have to install it from GitHub at this stage:

    "react-autosuggest": "moroshko/react-autosuggest#3.0"

I hope to release a beta version in the next week or so.

The [3.0 docs](https://github.com/moroshko/react-autosuggest/blob/3.0/README.md) are ready, so you should be good to go. I also created many [examples](https://github.com/moroshko/react-autosuggest/tree/3.0/demo/src/components/App/components) that should help.

Let me know if you have any issues upgrading, and I'll be happy to help.

**Comment by approots** [comment]
Ok. Thanks!

**Comment by moroshko** [comment]
@approots Just wanted to let you know that 3.0 alpha version is available on npm:

    npm install react-autosuggest@3.0.0-alpha.1 --save
