### ISSUE TITLE
focus?

### ISSUE THREAD

**Issue by acthp** [moroshko/react-autosuggest#65]
Question: Why re-implement focus, instead of using the browser built-in focus? And if re-implementing, why call it "focus", when that already means something else? It is very confusing that onSuggestionFocused is unrelated to the browser focus.

**Comment by approots** [comment]
Well there's no DOM concept of focus on select options - even if this were a native select component - so there's no way to use the "browser built-in focus". And it's not quite the same concept of selected options either, since the options aren't selected, just highlighted.

As for the name "onSuggestionFocused", I don't mind it. As mentioned, it couldn't be "onOptionSelected". Maybe "onOptionHighlighted"?

**Comment by acthp** [comment]
I like onOptionHighlighted. ;) But, whatever. The elements can be focused if you render them with anchor tags, same as any other drop-down menu.  If you add a custom render hook that returns an anchor tag, you will see that you now have two sets of controls (up/down, tab/shift-tab) that control two independent notions of "focus".

However I note that every other autocomplete widget I can find (jquery, etc.) also avoid browser focus on the options, so maybe there's a good reason for doing so... user expectation, accessibility, or something? Seems counter-intuitive to me. Autocomplete in other contexts, like the location bar, work with tab/shift-tab/return.

**Comment by moroshko** [comment]
@acthp Sorry for the late response. I can see how the name `onSuggestionFocused` can be confusing. Naming aside, is there any functionality issue you are trying to demonstrate, or is it purely the name?
