### ISSUE TITLE
This project needs additional maintainers

### ISSUE THREAD

**Issue by fatso83** [moroshko/react-autosuggest#672]
As is evident from the number of downloads and issues in the tracker, it's clear that this package is both useful and popular. But having close to 200 issues and 20 pull requests shows that you (@moroshko) might need a hand in the custodianship of the project!

From experience with many other open source projects, it's a good idea to invite a couple of "lieutenants"  on board to help with the mundane tasks. It doesn't mean you lose control of the project, but you get valuable help when the size of the project has grown beyond what one guy can fathom to support in his spare time.

My suggestion is that you add a "Help wanted" section to the top of the readme where you ask for co-maintainers and start tagging issues [with labels like "Help wanted", "Difficulty: easy", etc](https://github.com/sinonjs/sinon/issues/1702) to get people helping you out. It's nice getting some help :-)

**Comment by annjawn** [comment]
Wondering the same if maintainers are needed, looks like a popular library but hasn't been updated in a year or so. Will be happy to contribute.

**Comment by tfritsch-km** [comment]
@moroshko, you did great with this project (thanks a lot !) and I think everybody can easily understand you got a lot of work with other projects and no time to maintain this one. 
But it would be such a shame to see this awesome lib collapse given the number of people who are willing to help (see the 26 PR, it means something) and the user base that keeps growing even after this no-commit-year (https://www.npmtrends.com/react-autosuggest). 
As suggested by @fatso83, a call for maintainers in the README could be a good starting point :)

**Comment by moroshko** [comment]
Hey guys,
Thanks for the warm words!
I indeed struggle to find time to maintain this project, and would love to get help.
Please reach out to me on Twitter [@moroshko](https://twitter.com/moroshko) if you use `react-autosuggest` in your apps and have the capacity to push this project to the next level. It needs some ❤️.

**Comment by fatso83** [comment]
I already bit off more than I can chew with Sinon, so not for me, but I have tried [sharing the call for maintainers](https://twitter.com/kopseng/status/1201491459930763265) :-)

**Comment by ptolemybarnes** [comment]
I am also willing to help with this.

**Comment by aberezkin** [comment]
Hi everyone.

I'm now taking an effort to revive (#726) this project. @moroshko gave me collaboration rights so I'll try my best to make this library at least up to date with the mainstream. Nevertheless, as @fatso83 mentioned `react-autosuggest` is too big to be maintained by a single guy with some spare time (which I am) so I'll leave the call for maintainers in readme for some time.

For now the plan is:

1. Fix `npm install && npm test` (which is done in #726 which will be merged soon after some minor edits).
2. Update all the libs and build pipeline
3. Release a major version (since `react-autosuggest` is not compatible with old versions of `react` already)
4. Configure new build and deploy pipeline using github actions
5. And finally look through all of these issues and PRs

Also here's some things I would like to be done:

- merge react-autosuggest into this repo to make lib management easier
- get rid of `react-themeable` in favor of something more up to date (@moroshko advices in favor of "headless UI" used in `react-table` and `downshift`)

If you have any suggestions please contact me or fill an issue in this repo. Also if you are willing to help please do!

I hope together we can build a strong community around this repo.

**Comment by aberezkin** [comment]
Since there's a call for maintainers in readme I think it's ok to close that issue (at least to make a decrement in issue counter 😅)

**Comment by judygab** [comment]
Hi! I'm happy to contribute as well. Have been using react-autosuggest for a year now.

**Comment by aberezkin** [comment]
Hi! @judygab. What would you like to work on? There's an issue with list of major activities around this repo #734. I'm doing the part about test with cypress, you can choose something you would like to do.

**Comment by aberezkin** [comment]
@judygab TS definitions would be great. Also I wouldn't stop on defenitions. It would be nice if you can integrate TS into build pipeline so we can gradually rewrite code base to TS.

**Comment by judygab** [comment]
> @judygab TS definitions would be great. Also I wouldn't stop on defenitions. It would be nice if you can integrate TS into build pipeline so we can gradually rewrite code base to TS.

Yes sure, definitions would be just one of the steps.
