### ISSUE TITLE
React version compatibility

### ISSUE THREAD

**Issue by bmcneely** [moroshko/react-autosuggest#69]
Does this component absolutely need the latest version of React in order to work properly? If not, its package.json should allow for older versions of React as far back as it will still work, while still trying to use the latest one possible. Otherwise, trying to use this component in conjunction with other components that need older versions of React results in a conflict of peer dependencies.

**Comment by zawilliams** [comment]
Agreed. Just ran into this same issue.

**Comment by moroshko** [comment]
@bmcneely @zawilliams Sorry guys. I decided to limit react-autosuggest 2.0 to React 0.14 in order to reduce the overhead of creating branching based on the version of React (mainly because of the split of `react-dom` from `react`). You can always install a [previous version](https://github.com/moroshko/react-autosuggest/tree/d0e9bc05e1f653bb859bbc74b4c41e7c214bf2a1) that requires React 0.13.

**Comment by zawilliams** [comment]
Word. Thanks @moroshko!
