### ISSUE TITLE
Can't scroll autosuggestion list on mobile device

### ISSUE THREAD

**Issue by hannesj** [moroshko/react-autosuggest#73]
[This](https://github.com/moroshko/react-autosuggest/blob/v2.1.0/src/Autosuggest.js#L514) makes it possible to get faster feedback on mobile devices, but unfortunately it makes it impossible to scroll the list, as the onTouchStart fires also when starting to drag the list.

**Comment by moroshko** [comment]
@hannesj `onTouchStart` was added because iOS devices didn't pick up `onMouseDown` at all, so tapping a suggestion on iPhone, for example, was causing the suggestions list to close without updating the input value. That's the history behind `onTouchStart`.

Any ideas how to fix this? Pull request is welcome!

**Comment by bachstatter** [comment]
Hi! 
I made a PR using [react-tap-event-plugin]  (https://github.com/zilverline/react-tap-event-plugin). I added some thoughts as well. Please let me know what you think.

**Comment by moroshko** [comment]
Thanks a lot! Version 2.1.1 is on npm now
