### ISSUE TITLE
configure debounce delay

### ISSUE THREAD

**Issue by loopmode** [moroshko/react-autosuggest#76]
It would be great if we could configure the debounce delay time. Currently, it is hard-coded as 100ms, in Autosuggest.js ~line 63:

    this.suggestionsFn = debounce(props.suggestions, 100);

This can generate unnecessary load on the servers and I personally would like to set it to ~500ms for our particular project.

I can create a PR if you don't have time for this, but consider it as useful as I do.

**Comment by moroshko** [comment]
@loopmode I agree, it needs to be configurable. PR is welcome!

**Comment by loopmode** [comment]
basically an easy task, kind of finished. I struggle with getting an example running and line endings tho :) Hope i find time for a proper PR soon

**Comment by moroshko** [comment]
@loopmode In 3.0, debounce is not part of react-autosuggest anymore. Check out [this example](https://github.com/moroshko/react-autosuggest/tree/3.0/demo/src/components/App/components/DebouncedExample) to see how to implement debouncing.

    npm install react-autosuggest@3.0-latest --save

**Comment by avindra** [comment]
@moroshko : Your link does not work. Is there a way to debounce in the latest version?

**Comment by avindra** [comment]
To answer my own question, I was able to use `lodash` to debounce:

```
const debounce = require('lodash.debounce');

...
    this.onSuggestionsUpdateRequested = debounce(this.onSuggestionsUpdateRequested.bind(this), 300);
```

Something like that should work for you :+1:

**Comment by moroshko** [comment]
@avindra Sorry for the broken link, I fixed that. Have a look at [this example](http://codepen.io/moroshko/pen/KVaGJE).

**Comment by maksimgm** [comment]
@moroshko Really useful. Thank you for the demo link. You're a life saver :)

**Comment by muellermarkus** [comment]
Note that for autosuggestions, lodash's **`_.throttle` might often be a better fit** instead of `_.debounce`. 

`debounce` will wait with invoking `this.onSuggestionsUpdateRequested` until the user has stopped typing. If a user is typing a long query, **he will only get auto-suggestions when he pauses typing or has finished typing**. => So that `wait` milliseconds have passed since the last keystroke.

What you more likely want is the that `this.onSuggestionsUpdateRequested` does **get invoked while the user is typing, but not too often**, i.e. not on every keystroke. The `throttle` method offers exactly that. `this.onSuggestionsUpdateRequested` will get invoked at most every `wait` milliseconds. 

See lodash's documentation on [throttle](https://lodash.com/docs/4.17.11#throttle) for a more detailed description and this [blog post](https://css-tricks.com/debouncing-throttling-explained-examples/) for an in-depth comparison between `debounce` and `throttle`.

So I would rather suggest something like:

```
this.onSuggestionsUpdateRequested = throttle(this.onSuggestionsUpdateRequested.bind(this), 500);
```

**Comment by danwild** [comment]
For anyone wanting to do this with REDUX, and unsure where to add - I throttled the dispatch function (I'm using underscore), e.g.

```javascript
function mapDispatchToProps(dispatch) {
  return {
    onSuggestionsFetchRequested: _.throttle(
      ({ value }) => {
        dispatch(loadSuggestions(value));
      },
      500,
      { leading: false }
    )
  };
}
```
